# BryJu Sound - Netlify Configuration
[build]
  # Build command
  command = "npm run build"

  # Directory to publish
  publish = "dist"

  # Node version
  node_version = "18"

[build.environment]
  # Environment variables
  NODE_ENV = "production"
  NODE_OPTIONS = "--max_old_space_size=4096"

# Redirects and headers
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Cache static assets for 1 year
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images for 1 year
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Don't cache API responses
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Functions configuration (if using Netlify Functions)
[functions]
  directory = "netlify/functions"

# Form handling (if using Netlify Forms)
[forms]
  [forms."contact"]
    fields = ["name", "email", "message", "restaurant"]
    required = ["name", "email", "message"]

# Build optimization
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Image optimization
[[images]]
  remote_images = ["https://images.unsplash.com/.*", "https://.*\\.spotifycdn\\.com/.*"]

# Dev server
[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"

# Branch deploys
[[context.production.branches]]
  branch = "main"

[[context.deploy-preview.branches]]
  branch = "develop"

# Environment variables for different contexts
[context.production.environment]
  VITE_API_URL = "https://api.bryjusound.com/api/v1"
  VITE_APP_ENV = "production"

[context.deploy-preview.environment]
  VITE_API_URL = "https://dev-api.bryjusound.com/api/v1"
  VITE_APP_ENV = "staging"

[context.branch-deploy.environment]
  VITE_API_URL = "https://dev-api.bryjusound.com/api/v1"
  VITE_APP_ENV = "development"